export const genres = [
  { key: "action", label: "Action" },
  { key: "fpp", label: "First Person" },
  { key: "tpp", label: "Third Person" },
  { key: "rpg", label: "RPG" },
  { key: "horror", label: "Horror" },
  { key: "adventure", label: "Adventure" },
  { key: "simulation", label: "Simulation" },
  { key: "strategy", label: "Strategy" },
  { key: "sports", label: "Sports" },
  { key: "puzzle", label: "Puzzle" },
  { key: "platformer", label: "Platformer" },
  { key: "survival", label: "Survival" },
  { key: "sandbox", label: "Sandbox" },
  { key: "mmo", label: "MMO" },
  { key: "stealth", label: "Stealth" },
];

export const features = [
  { key: "single-player", label: "Single Player" },
  { key: "multiplayer", label: "Online Multiplayer" },
  { key: "local-multiplayer", label: "Local Multiplayer" },
  { key: "co-op", label: "Co-op" },
  { key: "cross-platform", label: "Cross Platform" },
  { key: "vr", label: "VR Support" },
  { key: "ar", label: "AR Support" },
  { key: "controller-support", label: "Controller Support" },
  { key: "modding", label: "Modding Support" },
  { key: "achievements", label: "Achievements" },
  { key: "leaderboards", label: "Leaderboards" },
  { key: "cloud-saves", label: "Cloud Saves" },
  { key: "ray-tracing", label: "Ray Tracing" },
  { key: "photo-mode", label: "Photo Mode" },
  { key: "dlc", label: "Downloadable Content (DLC)" },
];
